export const DRAFTS = [
  {
    id: 'draft-1',
    subject: 'Draft: Project update for client',
    preview: 'Hi team, I wanted to share the latest status on the Mailgent integration and the next steps for the client deliverables...',
    body: 'Hi team, I wanted to share the latest status on the Mailgent integration and the next steps for the client deliverables. We are on track to finish the API sync by Thursday. I will send the final summary document once the review is complete.',
    updated: '10:12 AM',
    label: 'Client',
    draftStatus: 'Waiting for review',
    recipients: 'client@company.com',
  },
  {
    id: 'draft-2',
    subject: 'Reply to HR about interview schedule',
    preview: 'Hi HR, thanks for the update. I am available on Tuesday afternoon or Wednesday morning for the interview. Please let me know which slot works best.',
    body: 'Hi HR, thanks for the update. I am available on Tuesday afternoon or Wednesday morning for the interview. Please let me know which slot works best. If those are not available, I can also make time later in the week.',
    updated: 'Yesterday',
    label: 'HR',
    draftStatus: 'Needs follow-up',
    recipients: 'hr@company.com',
  },
  {
    id: 'draft-3',
    subject: 'Draft: meeting summary for team',
    preview: 'Summary: We reviewed the roadmap, agreed on the next sprint priorities, and assigned action items for the marketing and engineering teams...',
    body: 'Summary: We reviewed the roadmap, agreed on the next sprint priorities, and assigned action items for the marketing and engineering teams. Please review the attached notes and add any comments before the Friday checkpoint.',
    updated: 'Yesterday',
    label: 'Meetings',
    draftStatus: 'Ready to send',
    recipients: 'team@company.com',
  },
  {
    id: 'draft-4',
    subject: 'Follow-up on invoice clarification',
    preview: 'Please confirm whether the invoice line item includes the additional consulting hours from last week, so we can process payment by Friday.',
    body: 'Please confirm whether the invoice line item includes the additional consulting hours from last week, so we can process payment by Friday. I want to make sure we avoid any incorrect billing before the month closes.',
    updated: '2 days ago',
    label: 'Finance',
    draftStatus: 'Review pending',
    recipients: 'finance@company.com',
  },
  {
    id: 'draft-5',
    subject: 'Draft: onboarding email to new member',
    preview: 'Welcome aboard! Here are the next steps for your first week, including the onboarding call, access details, and teammate introductions.',
    body: 'Welcome aboard! Here are the next steps for your first week, including the onboarding call, access details, and teammate introductions. Please let me know if you need anything before our first sync.',
    updated: '2 days ago',
    label: 'HR',
    draftStatus: 'Needs details',
    recipients: 'newhire@company.com',
  },
]
